### PR TITLE
add quick tag to default port scan plugin

### PR DESCRIPTION
**Pull request by gr4ysku11**
add quick tag to default port scan plugin

### CODE REVIEW

**Comment by Tib3rius** [comment]
Hey @gr4ysku11, I'm not against this merge per se, but could you explain your reasoning for the tag? Is it just so you can only run that particular port scan plugin?

**Comment by gr4ysku11** [comment]
Yeah that's pretty much it. I noticed the AllTCPPortScan had a 'long' tag associated with it, so figured it might be useful for the quick scan.

**Comment by Tib3rius** [comment]
The "long" tag is generally used as an exclusion tag (i.e. run everything except "long" tagged plugins). If you just want to run the top tcp ports plugin you could use --port-scans=top-tcp-ports since plugin slugs (the shortened version of their name) can be used as tags too.

My worry about having "quick" is that it could apply to other non port scan plugins too, so we'd have to update anything that realistically runs "quickly", otherwise it might confuse people. It's worth thinking about though.

**Comment by gr4ysku11** [comment]
Ah I didn't realize they could be used for exclusion. I'll close this then, thanks.

**Pull request closed without merging**
