### PR TITLE
Additional options

### PR DESCRIPTION
**Pull request by svo80**
I added some additional improvements:

- Target list can be read from a file.
- Programs are called with their absolute path for security reasons.
- Execution of service enumeration programs can be skipped to save time. Respective programs are only documented.
- Introduced a complexity level for service enumeration programs to support only executing a group of programs and balance time and extracted information.
- Total scanning time is measured.
- Some additional minor changes regarding documentation, output, and service patterns.

### CODE REVIEW

**Comment by unk1nd0n3** [comment]
Hi Tib3rius,

do you  plan to merge PR? Thanks

**Comment by svo80** [comment]
Hi,

I also opened a new branch that contains additional commits. I will likely create my own repository at some point. Autorecon by Tib3rius is a great tool, and I added quite some features in my branch. Please feel free to take a look.

**Comment by unk1nd0n3** [comment]
Hi,

nice. I expected somebody will do code review of your PR because i'm too lazy. By the way did you think about to add masscan as prestage for nmap scanning?

I found that this is a common practice now (saw this in HTB writeups)

**Comment by svo80** [comment]
Hi,

I did not include massscan yet, because I did not want to modify my Kali machine too much before the OSCP exam. It is basically only a matter of adding a new entry in a configuration file though, and I will do so shortly. For any application that is defined in the configuration file, my branch also supports automatically checking that the respective program exists to avoid potential later errors at runtime.

**Comment by Tib3rius** [comment]
@svo80 hey, sorry I didn't get a notification for this. I'll look over the modifications. I'm going to have to reject the absolute path one right off the bat though. I don't agree that it's a security risk, this is a tool that you should be running on your own system, therefore you should know what is installed. Absolute paths for tools will break compatibility across multiple operating systems.

Also, it would be far better for me in the future if you broke up your improvements into smaller pull requests, rather than pushing a huge merge of features. Makes things easier to review. Thanks!

**Comment by Tib3rius** [comment]
Actually, having just skimmed over some of the changes, I'm going to reject this outright. I appreciate the effort, and maybe you can resubmit, however I have the following objections:

1. Renaming the tool. I don't see a reason for that.
2. You've removed almost all of the README.
3. I'm not sure adding more configuration files is in the best interests of usability. I'm also unsure why you've made the existing config files more complex (e.g. why are all port scans now prefixed with "port-scan"?)
4. What is the purpose of custom.toml?

I really do appreciate the efforts here, but I feel like you need to submit smaller changes and explain what they are doing and the reasons for them. There's just too much here to process, and I'm not sure why you've changed this which you don't need to, like the name and the entire README file.

**Comment by svo80** [comment]
Hi Tib3rius,

I created the pull request after the first change. Since then, there were several other commits, and I created a new branch which is kept up to date. Essentially, this will become a new program, and this is why I also changed the name. It was unclear whether you are still maintaining your repository, and I added a number of new features in my branch and am partially moving the program into other directions.

Best regards

**Comment by Tib3rius** [comment]
I am maintaining this repository, I was just taking a short break after passing the OSCP. If you don't want to collaborate on this that is up to you, I can manually integrate some of your changes myself.

Kind regards,

Tib3rius

**Pull request closed without merging**
