### PR TITLE
autorecon.py: fixed stdin/stdout issue

### LINKED ISSUE #1: Cannot write to terminal after AutoRecon finishes.
This is a known issue which appears to be infrequent. Sometimes when AutoRecon finishes running, or the user cancels execution, anything typed into the terminal doesn't get displayed. Commands still appear to get executed.

A workaround is to run the command: reset

### PR DESCRIPTION
**Pull request by the-c0d3r**
Fixes #1

### CODE REVIEW

**Comment by the-c0d3r** [comment]
Please test out this latest commit, based on what @VortixDev mentioned in #1 
As far as I have tested, it seem to resolve the issue. 

@six2dez @Tib3rius

**Comment by six2dez** [comment]
> Please test out this latest commit, based on what @VortixDev mentioned in #1
> As far as I have tested, it seem to resolve the issue.
> 
> @six2dez @Tib3rius

Solved! Thanks a lot!

**Comment by Tib3rius** [comment]
Thanks for the work on this. I will try it out soon and merge it. On vacation at the moment.

**Comment by Tib3rius** [comment]
@the-c0d3r I'm getting the following error in Bash (on Kali) when the program exits, or I Ctrl+C it:

> Error in atexit._run_exitfuncs:
> Traceback (most recent call last):
>   File "autorecon.py", line 27, in _quit
>     termios.tcsetattr(sys.stdin.fileno(), TERM_FLAGS)
> TypeError: tcsetattr() takes exactly 3 arguments (2 given)

The docs indicate that the following arguments are needed:

> termios.tcsetattr(fd, when, attributes)

Which one are we missing?

**Comment by the-c0d3r** [comment]
@Tib3rius well, this is embarrasing, it looks like I forgotten one paramter for the setattr call. But the weird thing is I should have caught this when I tested locally so many times.

**Comment by Tib3rius** [comment]
@the-c0d3r no problem at all, it happens! I'll check this out now and confirm everything works.

**Comment by Tib3rius** [comment]
@the-c0d3r it seems to be working when AutoRecon finishes normally, but yeah, Ctrl-C is still having issues. I'll have to look into how to catch those errors more gracefully I think. For now, this should resolve the main bug. Thanks for all your hard work!

**Pull request merged**
